# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
name: nf-core CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master
  release:
    types:
      - "published"

env:
  NXF_ANSI_LOG: false
  NFTEST_VER: "0.7.3"

# cancel-in-progress: true ensures that if a new push is made to the same branch while a previous run is still in progress, the previous run is cancelled
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test-dev:
    # Only run if the pull request is against the dev branch or if the push is to the dev branch
    if: (github.base_ref == 'dev' || (github.event_name == 'push'))
    name: Run pipeline with test data on dev
    runs-on: ubuntu-latest
    # Define the matrix of different Nextflow versions to test
    strategy:
      matrix:
        NXF_VER:
          - "latest-everything"
        profile: # TODO ["singularity", "conda"]
          - "docker"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      # Install Nextflow
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      # Install nf-test
      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash -s $NFTEST_VER
          sudo mv nf-test /usr/local/bin/

      # Run nf-test
      - name: Run nf-test
        run: nf-test test tests/pipeline/ --profile "test,${{ matrix.profile }}" --tap=test.tap

      - uses: pcolby/tap-summary@v1
        with:
          path: >-
            test.tap

      # If the test fails, output the software_versions.yml using the 'batcat' utility
      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always /home/runner/work/fetchngs/fetchngs/.nf-test/tests/*/output/pipeline_info/software_versions.yml

  test-master:
    # Only run on master branch or when a PR is opened against master
    if: github.base_ref == 'master'
    name: Run pipeline with test data on master
    runs-on: ubuntu-latest
    # Define the matrix of different Nextflow versions to test
    strategy:
      matrix:
        NXF_VER:
          - "22.10.1"
          - "latest-everything"
        profile:
          - "docker"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      # Install Nextflow
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      # Install nf-test
      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash -s $NFTEST_VER
          sudo mv nf-test /usr/local/bin/

      # Run nf-test
      - name: Run nf-test
        run: nf-test test tests/pipeline/ --profile "test,${{ matrix.profile }}" --tap=test.tap

      - uses: pcolby/tap-summary@v1
        with:
          path: >-
            test.tap

      # If the test fails, output the software_versions.yml using the 'batcat' utility
      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always /home/runner/work/fetchngs/fetchngs/.nf-test/tests/*/output/pipeline_info/software_versions.yml
